pantalla:
 ancho: 1024
 alto: 800

configuracion: 
 vel_personaje : 3
 margen_scroll : 30

tipos:
- nombre: arbol
  imagen: path/a/imagen.png

- nombre: castillo
  imagen: ../Taller/Images/Industrial_Age/castillo.png
  ancho_base: 2
  alto_base: 2
  pixel_ref_x: 30
  pixel_ref_y: 40

- nombre: Church
  imagen: ../Taller/Images/Industrial_Age/Church.png
  ancho_base: 3
  alto_base: 3
  
- nombre: Consulate
  imagen: ../Taller/Images/Industrial_Age/Consulate.png
  ancho_base: 3
  alto_base: 3
  
- nombre: Town_Hall
  imagen: ../Taller/Images/Industrial_Age/Town_Hall.png
  ancho_base: 3
  alto_base: 3

- nombre: soldado
  imagen: path/a/imagen.png
  fps: 10
  delay: 5

- nombre: juana_de_arco
  imagen: path/a/imagen.png
  fps: 10

- nombre: tierra
  imagen: path/a/imagen.png

- nombre: agua
  imagen: path/a/imagen.png

escenario:
  nombre: orleans
  size_x: 100
  size_y: 100
  entidades:
  - {x: 10, y: 15, tipo: tierra}
  - {x: 15, y: 20, tipo: tierra} 
  - {x: 10, y: 15, tipo: agua} 
  - {x: 10, y: 10, tipo: castillo}
  - {x: 0, y: 0, tipo: Church} 
  - {x: 9, y: 2, tipo: Consulate} 
  - {x: 2, y: 10, tipo: Town_Hall}
  
  
  protagonista: 
   tipo: juana_de_arco 
   x: 50 
   y: 50 
